### PR TITLE
chips company list

### PR DESCRIPTION
**Pull request by shahrilamrias**
- fancy upload buttons (resume card)
- Company List uses chips instead of buttons in list. We can extend the
  chips to act as a filter for the job application list.

### CODE REVIEW

**Comment by shahrilamrias** [comment]
aku baru perasan. ko remove dist/ https://github.com/cyberhax/internApp/commit/112291868146f5285d9b3928716f3090c829fc5c whyyyyy

**Comment by fadziljusri** [comment]
chipsmore?

**Comment by khursani8** [comment]
perlu ke dist tu?

**Comment by shahrilamrias** [comment]
> perlu ke dist tu?

xsure haha. rase build file je

**Comment by khursani8** [comment]
sbb tu aku buang XP
tp klau ko nk utk check aku dh push balik

**Comment by khursani8** [comment]
pushed to heroku master

**Pull request closed without merging**
